[Application Options]
listen=0.0.0.0:9735
externalip=5.78.207.205:9735
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
tlsautorefresh=true

[Bitcoin]
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=neutrino

[Neutrino]
neutrino.addpeer=btcd-mainnet.lightning.computer
neutrino.addpeer=mainnet1-btcd.zaphq.io
neutrino.addpeer=mainnet2-btcd.zaphq.io
neutrino.addpeer=bb1.breez.technology
neutrino.addpeer=node.blixtwallet.com

# Required for Neutrino mainnet in v0.18+
